apiVersion: router.agentic-layer.ai/v1alpha1
kind: ModelRouter
metadata:
  labels:
    app.kubernetes.io/name: model-router-operator
    app.kubernetes.io/managed-by: kustomize
  name: modelrouter-sample
spec:
  # TODO(user): Add fields here
